name: "convolutional Seq2Seq"
joeynmt_version: "2.0.0"

data:
    # generate data with scripts/generate_reverse_task.py
    train: "test/data/reverse/train"
    dev: "test/data/reverse/dev"
    test: "test/data/reverse/test"
    dataset_type: "plain"
    src:
        lang: "src"
        max_length: 25
        level: "word"
        voc_limit: 100
        voc_min_freq: 0
    trg:
        lang: "trg"
        max_length: 25
        level: "word"
        voc_limit: 100
        voc_min_freq: 0

testing:
    n_best: 1
    beam_size: 1
    beam_alpha: 1.0
    eval_metrics: ["bleu"]
    max_output_length: 30
    batch_size: 10
    batch_type: "sentence"
    return_prob: "none"

training:
    loss: "crossentropy"            
    label_smoothing: 0.1
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.0002
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 10
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    early_stopping_metric: "bleu"
    epochs: 1
    validation_freq: 1000
    logging_freq: 100
    model_dir: "reverse_transformer"
    overwrite: True
    shuffle: True
    use_cuda: False
    fp16: True
    print_valid_sents: [0, 3, 6]
    keep_best_ckpts: 2
model:
  initializer: "normal" 
  linear_initializer: "normal"
  eembed_initializer: "normal"    
  embed_init_weight: 0.1          
  bias_initializer: "zeros"       
  encoder:
    type: "convolutional"
    layers: 
      layer 1:
          output_channels: 512
          kernel_width: 3 
          residual: True
      layer 2:
          output_channels: 287
          kernel_width: 3 
          residual: True
    num_layers: 512
    dropout: 0.1
    embeddings:
            embedding_dim: 64
  decoder:
    type: "convolutional"
    layers: 
      layer 1:
          output_channels: 512
          kernel_width: 3 
          residual: True
      layer 2:
          output_channels: 287
          kernel_width: 3 
          residual: True
    num_layers: 512
    dropout: 0.1
    embeddings:
            embedding_dim: 64
